site_name: MUBen - Documentation

nav:
  - About: index.md
  - Get Started: started.md
  - Project Overview: overview.md
  - muben.args: muben.args.md
  - muben.layers: muben.layers.md
  - muben.dataset: muben.dataset.md
  - muben.train: muben.train.md
  - muben.utils: muben.utils.md
  - Customization: customize.md

theme: readthedocs

markdown_extensions:
  - admonition

extra_css: [extra.css]