site_name: MUBen - Documentation

nav:
  - About MUBen:
    - About: index.md
    - Get Started: started.md
  - MUBen API:
    - Overview: overview.md
    - muben.args: muben.args.md
    - muben.layers: muben.layers.md
    - muben.dataset: muben.dataset.md
    - muben.train: muben.train.md
    - muben.utils: muben.utils.md
  - Examples:
    - Customization: customize.md

theme: readthedocs

markdown_extensions:
  - admonition

extra_css: [extra.css]